services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: .
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: celery -A logic.queue.celery_app:app worker --loglevel=info

  celery_beat:
    container_name: celery_beat
    build: .
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: celery -A logic.queue.celery_app:app beat --loglevel=info

  bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app

volumes:
  mongo_data: